#     __ __    ___   ____  _     ______  __ __     _____ ______   ____  ______  __ __  _____
#    |  |  |  /  _] /    || |   |      ||  |  |   / ___/|      | /    ||      ||  |  |/ ___/
#    |  |  | /  [_ |  o  || |   |      ||  |  |  (   \_ |      ||  o  ||      ||  |  (   \_
#    |  _  ||    _]|     || |___|_|  |_||  _  |   \__  ||_|  |_||     ||_|  |_||  |  |\__  |
#    |  |  ||   [_ |  _  ||     | |  |  |  |  |   /  \ |  |  |  |  _  |  |  |  |  :  |/  \ |
#    |  |  ||     ||  |  ||     | |  |  |  |  |   \    |  |  |  |  |  |  |  |  |     |\    |
#    |__|__||_____||__|__||_____| |__|  |__|__|    \___|  |__|  |__|__|  |__|   \__,_| \___|
#
#     By RealAstro
# Please make sure to use §  for colors, other symbols may not work and can cause major issues.
# If you're facing any issues with this plugin please open an issue i'll respond as fast as possible
#
# Variables:
# - %CurrentHealth% => Displays the player's current health.

NameTag-Format: "§f%CurrentHealth% §c❤"